name: quality

on:
  push:
    branches:
      - main
  pull_request:
    types:  [opened, synchronize, reopened]

jobs:
  quality:
    name: Build and Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout quotonic
        uses: actions/checkout@v3
      
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run pre-commit
        run: pre-commit run -a --show-diff-on-failure

      - name: Run mypy
        run: mypy